# AVNav Kiosk configuration
# Place this file on the tablet at /sdcard/avnavkiosk.conf

# AVNav server URL
serverUrl=http://192.168.30.10:8080

# AVNav server Wi-Fi SSID.
# AVNavKiosk checks this before starting the WebView.
wifiSSID=seascamp1

# Startup splash/banner image
bannerFileName=avnav-banner.png

# Splash text shown on startup. Use \n for newlines.
splashText=Welcome to Sea Scamp AVNav\nPlease check that the server is ready (red light\non the instrument panel)\nand then touch the screen to start

# Splash text size (sp)
splashTextSize=25

# Keep screen awake
keepScreenOn=true

# Hide Android system UI
hideStatus=true
hideNavigation=true

# Lock orientation to portrait if true, landscape if false.
portraitLock=false
